// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Naruto_Universe.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Naruto_Universe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NChakraNatureNCharacter", b =>
                {
                    b.Property<int>("ChakraNaturesId")
                        .HasColumnType("integer");

                    b.Property<int>("NCharactersId")
                        .HasColumnType("integer");

                    b.HasKey("ChakraNaturesId", "NCharactersId");

                    b.HasIndex("NCharactersId");

                    b.ToTable("NChakraNatureNCharacter");
                });

            modelBuilder.Entity("NCharacterNJutsu", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("integer");

                    b.Property<int>("JutsusId")
                        .HasColumnType("integer");

                    b.HasKey("CharactersId", "JutsusId");

                    b.HasIndex("JutsusId");

                    b.ToTable("NCharacterNJutsu");
                });

            modelBuilder.Entity("NCharacterNMedia", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaListId")
                        .HasColumnType("integer");

                    b.HasKey("CharactersId", "MediaListId");

                    b.HasIndex("MediaListId");

                    b.ToTable("NCharacterNMedia");
                });

            modelBuilder.Entity("NJutsuNJutsuClassification", b =>
                {
                    b.Property<int>("JutsuClassificationsId")
                        .HasColumnType("integer");

                    b.Property<int>("JutsusId")
                        .HasColumnType("integer");

                    b.HasKey("JutsuClassificationsId", "JutsusId");

                    b.HasIndex("JutsusId");

                    b.ToTable("NJutsuNJutsuClassification");
                });

            modelBuilder.Entity("NJutsuNMedia", b =>
                {
                    b.Property<int>("JutsusId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaListId")
                        .HasColumnType("integer");

                    b.HasKey("JutsusId", "MediaListId");

                    b.HasIndex("MediaListId");

                    b.ToTable("NJutsuNMedia");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NArc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NArcs");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NChakraNature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NChakraNatures");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int?>("ClanId")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int?>("KekkeiGenkaiId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("VillageId")
                        .HasColumnType("integer");

                    b.Property<int?>("VillageStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("KekkeiGenkaiId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("VillageId");

                    b.ToTable("NCharacters");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NClan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NClans");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NCountries");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NJutsu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<int[]>("Classes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NJutsus");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NJutsuClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NJutsuClassifications");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NKekkeiGenkai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NKekkeiGenkais");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("EntryIndex")
                        .HasColumnType("integer");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<int>("NArcId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NArcId");

                    b.HasIndex("EntryIndex", "MediaType")
                        .IsUnique();

                    b.ToTable("NMediae");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NVillage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NVillages");
                });

            modelBuilder.Entity("NChakraNatureNCharacter", b =>
                {
                    b.HasOne("Naruto_Universe.Model.DbEntity.NChakraNature", null)
                        .WithMany()
                        .HasForeignKey("ChakraNaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Naruto_Universe.Model.DbEntity.NCharacter", null)
                        .WithMany()
                        .HasForeignKey("NCharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NCharacterNJutsu", b =>
                {
                    b.HasOne("Naruto_Universe.Model.DbEntity.NCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Naruto_Universe.Model.DbEntity.NJutsu", null)
                        .WithMany()
                        .HasForeignKey("JutsusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NCharacterNMedia", b =>
                {
                    b.HasOne("Naruto_Universe.Model.DbEntity.NCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Naruto_Universe.Model.DbEntity.NMedia", null)
                        .WithMany()
                        .HasForeignKey("MediaListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NJutsuNJutsuClassification", b =>
                {
                    b.HasOne("Naruto_Universe.Model.DbEntity.NJutsuClassification", null)
                        .WithMany()
                        .HasForeignKey("JutsuClassificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Naruto_Universe.Model.DbEntity.NJutsu", null)
                        .WithMany()
                        .HasForeignKey("JutsusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NJutsuNMedia", b =>
                {
                    b.HasOne("Naruto_Universe.Model.DbEntity.NJutsu", null)
                        .WithMany()
                        .HasForeignKey("JutsusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Naruto_Universe.Model.DbEntity.NMedia", null)
                        .WithMany()
                        .HasForeignKey("MediaListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NCharacter", b =>
                {
                    b.HasOne("Naruto_Universe.Model.DbEntity.NClan", "Clan")
                        .WithMany("NCharacters")
                        .HasForeignKey("ClanId");

                    b.HasOne("Naruto_Universe.Model.DbEntity.NKekkeiGenkai", "KekkeiGenkai")
                        .WithMany("Characters")
                        .HasForeignKey("KekkeiGenkaiId");

                    b.HasOne("Naruto_Universe.Model.DbEntity.NVillage", "Village")
                        .WithMany("Characters")
                        .HasForeignKey("VillageId");

                    b.Navigation("Clan");

                    b.Navigation("KekkeiGenkai");

                    b.Navigation("Village");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NJutsu", b =>
                {
                    b.HasOne("Naruto_Universe.Model.DbEntity.NCharacter", null)
                        .WithMany()
                        .HasForeignKey("CreatorId");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NMedia", b =>
                {
                    b.HasOne("Naruto_Universe.Model.DbEntity.NArc", "Arc")
                        .WithMany("MediaList")
                        .HasForeignKey("NArcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arc");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NVillage", b =>
                {
                    b.HasOne("Naruto_Universe.Model.DbEntity.NCountry", "Country")
                        .WithMany("NVillages")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NArc", b =>
                {
                    b.Navigation("MediaList");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NClan", b =>
                {
                    b.Navigation("NCharacters");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NCountry", b =>
                {
                    b.Navigation("NVillages");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NKekkeiGenkai", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Naruto_Universe.Model.DbEntity.NVillage", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
